mkl_support: # [linux64 or win64]
  - nomkl    # [linux64 or win64]
  - mkl      # [linux64 or win64]

mkl:         # [linux64 or win64]
  - 2023.2   # [linux64 or win64]

mkl_devel:   # [linux64 or win64]
  - 2023.2   # [linux64 or win64]

