{% set version = "2.12.0" %}
{% set build = 0 %}
{% set build_string = "" %}

{% set build_string = "mkl_" %}  # [(linux64 or win64) and mkl_support == 'mkl']
{% set build = build + 100 %}                # [(linux64 or win64) and mkl_support != 'mkl']

package:
  name: numexpr
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/numexpr/numexpr-{{ version }}.tar.gz
  sha256: f552b9b4b2cbfa21f38c6f11ddd2db88eb5482364fe21f0b19482e95899796bb

build:
  skip: true  # [py<39]
  # pypy not participating in numpy2 migration; numexpr not buildable anymore with numpy 1.x
  skip: true  # [python_impl == "pypy"]
  string: "{{ build_string }}py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  number: {{ build }}
  script: bash {{ RECIPE_DIR }}/build_without_mkl.sh  # [unix and not (linux64 and mkl_support == 'mkl')]
  script: bash {{ RECIPE_DIR }}/build_with_mkl.sh  # [linux64 and mkl_support == 'mkl']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - mkl                                    # [(linux64 or win64) and mkl_support == 'mkl']
    - mkl-devel                              # [(linux64 or win64) and mkl_support == 'mkl']
    - numpy >=2
    - pip
    - python
    - setuptools
  run:
    - libblas * *mkl                         # [(linux64 or win64) and mkl_support == 'mkl']
    - mkl                                    # [(linux64 or win64) and mkl_support == 'mkl']
    - nomkl                                  # [(linux64 or win64) and mkl_support != 'mkl']
    - python
    - numpy >=1.23.0

test:
  imports:
    - numexpr
    - numexpr.interpreter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydata/numexpr
  license: MIT
  license_file: LICENSE.txt
  summary: Fast numerical expression evaluator for NumPy.
  description: |
    Numexpr is a fast numerical expression evaluator for NumPy. With it,
    expressions that operate on arrays (like "3*a+4*b") are accelerated and use
    less memory than doing the same calculation in Python.
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  dev_url: https://github.com/pydata/numexpr

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - scopatz
    - djkirkham
